# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solvedrive',
                'doc_host': 'https://answerDotAI.github.io',
                'git_url': 'https://github.com/answerDotAI/solvedrive',
                'lib_path': 'solvedrive'},
  'syms': {'solvedrive.core': {'solvedrive.core.foo': ('core.html#foo', 'solvedrive/core.py')}}}
