"""User facing API for solvedrive

Docs: https://answerDotAI.github.io/solvedrive/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['FIELDS', 'FOLDER_MIME', 'Drive', 'hsize', 'File', 'Folder', 'Files']

# %% ../nbs/00_core.ipynb #4d53f263
from fastcore.all import *
from fastgws import Drive as GDrive
from fastgws.auth import *
from uuid import uuid4

import json, mimetypes, sys

# %% ../nbs/00_core.ipynb #f4e588b0
FIELDS = 'id,name,mimeType,size,modifiedTime,parents,trashed,webViewLink'

class Drive:
    def __init__(self, client): self.client = client

    @classmethod
    async def init(cls, scopes='readonly', creds=None, redirect_uri='https://oauth.appapis.org/redirect',
        listen=False, port=0, open_url=print):
        if scopes == 'full': scopes = ['https://www.googleapis.com/auth/drive']
        else:                scopes = [f'https://www.googleapis.com/auth/drive.{x}' for x in listify(scopes)]
        if creds is None: creds = await oauth_creds(scopes=scopes, redirect_uri=redirect_uri, listen=listen, port=port, open_url=open_url)
        return cls(GDrive(creds=creds))

    async def about(self):
        "User resource with `email` attribute"
        d = await self.client.about.get(fields='user')
        return AttrDict(d.user, email=d.user.emailAddress)

# %% ../nbs/00_core.ipynb #fe25d3be
FOLDER_MIME = 'application/vnd.google-apps.folder'

def hsize(n):
    "Human-readable byte size"
    for u in ' KMGT':
        if n < 1024: return f'{n:.0f}{u.strip()}B' if u==' ' else f'{n:.1f}{u}B'
        n /= 1024
    return f'{n:.1f}PB'

def _mtype(m): return m.split('.')[-1] if m.startswith('application/vnd.google-apps') else m

def _link(f):
    "File name as an anchor opening it in Drive in a new tab"
    nm = f.get('name') or ''
    return f'<a href="{url}" target="_blank">{nm}</a>' if (url:=f.get('webViewLink')) else nm

class File(AttrDict):
    def __init__(self, drive, d):
        super().__init__(d)
        self.drive = drive

    def _desc(self, nm):
        sz = f', {hsize(int(self.size))}' if self.get('size') else ''
        trash = '🗑' if self.get('trashed') else ''
        return f'{type(self).__name__}({self.id}: {trash}{nm} ({_mtype(self.get("mimeType", ""))}{sz}) {self.get("modifiedTime", "")})'

    def __repr__(self): return self._desc(self.get('name', ''))
    def _repr_markdown_(self): return self._desc(_link(self))

    async def refresh(self, fields=FIELDS):
        self.update(await self.drive.client.files.get(file_id=self.id, fields=fields))
        return self

    @classmethod
    async def fetch(cls, drive, id): return await cls(drive, dict(id=id)).refresh()

class Folder(File): pass

def _fid(f): return f.id if isinstance(f, File) else f

def _mk_file(drive, d):
    cls = Folder if d.get('mimeType')==FOLDER_MIME else File
    return cls(drive, d)

# %% ../nbs/00_core.ipynb #a5cc3392
_upload_url = 'https://www.googleapis.com/upload/drive/v3/files'

def _multipart_related(meta, data, mime):
    b = uuid4().hex
    body = (f'--{b}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n{json.dumps(meta)}\r\n'
        f'--{b}\r\nContent-Type: {mime}\r\n\r\n').encode() + data + f'\r\n--{b}--'.encode()
    return body, {'Content-Type': f'multipart/related; boundary={b}'}

@patch
async def upload(self:Drive,
    path=None,   # File to upload
    name=None,   # Name in Drive (defaults to `path`'s name)
    data=None,   # Content bytes, as an alternative to `path`
    mime=None,   # Content type (guessed from `name` if not given)
    folder=None, # Destination `Folder` or folder id (default: My Drive root)
):
    "Upload a file to Drive, returning the new `File`"
    if path:
        p = Path(path)
        name, data = name or p.name, p.read_bytes()
    mime = mime or mimetypes.guess_type(name)[0] or 'application/octet-stream'
    meta = dict(name=name)
    if folder: meta['parents'] = [_fid(folder)]
    body, hdrs = _multipart_related(meta, data, mime)
    r = await self.client.transport.request('POST', _upload_url, content=body, headers=hdrs,
        params=dict(uploadType='multipart', fields=FIELDS))
    return _mk_file(self, r)

# %% ../nbs/00_core.ipynb #d7fe7a99
def _file_row(f):
    sz = hsize(int(f.size)) if f.get('size') else ''
    return f'| {f.id} | {"🗑" if f.get("trashed") else ""}{_link(f)} | {_mtype(f.get("mimeType") or "")} | {sz} | {(f.get("modifiedTime") or "")[:10]} |'

_file_hdr = '| id | name | type | size | modified |\n|-|-|-|-|-|\n'
class Files(L):
    def __init__(self, d, *rest, drive=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self.drive = drive

    def _repr_markdown_(self): return _file_hdr + '\n'.join(self.map(_file_row))

@patch
async def search_files(self:Drive, q=None, max_results=20, fields=FIELDS, **kwargs):
    r = await self.client.files.list(q=q, page_size=max_results, fields=f'files({fields})', **kwargs)
    return Files(L(r.get('files') or []).map(lambda o: _mk_file(self, o)), drive=self)

# %% ../nbs/00_core.ipynb #c5cc0e5e
_exports = {'application/vnd.google-apps.document': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.google-apps.spreadsheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.google-apps.presentation': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.google-apps.drawing': 'image/png'}

@patch
async def download(self:File,
    save=None, # Optional path to also write the bytes to (a directory uses the file's name)
    mime=None, # Export format for Google-native files
):
    "File content as bytes; Google-native files are exported (docx/xlsx/pptx by default)"
    native = self.mimeType.startswith('application/vnd.google-apps')
    if not native:
        if mime: raise ValueError(f'`mime` is for exporting Google-native files; {self.name} is {self.mimeType}')
        r = await self.drive.client.files.get(file_id=self.id, alt='media', raw=True)
    else: r = await self.drive.client.files.export(file_id=self.id, mime_type=mime or _exports[self.mimeType], raw=True)
    data = r.content
    if save:
        p = Path(save)
        if p.is_dir(): p = p/self.name
        p.write_bytes(data)
    return data

# %% ../nbs/00_core.ipynb #52081533
@patch
async def create_folder(self:Drive, name, parent=None):
    "Create a folder, returning the new `Folder`"
    meta = dict(name=name, mime_type=FOLDER_MIME, fields=FIELDS)
    if parent: meta['parents'] = [_fid(parent)]
    return Folder(self, await self.client.files.create(**meta))

@patch
async def ls(self:Folder, q=None, **kwargs):
    "Search within this folder"
    qs = f"'{self.id}' in parents and trashed=false"
    if q: qs = f'{qs} and ({q})'
    return await self.drive.search_files(qs, **kwargs)

@patch
@delegates(Drive.upload)
async def upload(self:Folder, path=None, **kwargs):
    "Upload into this folder"
    return await self.drive.upload(path, folder=self, **kwargs)

# %% ../nbs/00_core.ipynb #859523ef
@patch
async def rename(self:File, name):
    "Rename to `name`"
    return self.update(await self.drive.client.files.update(file_id=self.id, name=name, fields=FIELDS))

@patch
async def move(self:File, folder):
    "Move into `folder` (a `Folder` or folder id)"
    return self.update(await self.drive.client.files.update(file_id=self.id, add_parents=_fid(folder),
        remove_parents=','.join(self.get('parents') or []), fields=FIELDS))

@patch
async def copy(self:File, name=None, folder=None):
    "Server-side copy, optionally renamed into `folder`; returns the new `File`"
    meta = dict(file_id=self.id, fields=FIELDS)
    if name: meta['name'] = name
    if folder: meta['parents'] = [_fid(folder)]
    return _mk_file(self.drive, await self.drive.client.files.copy(**meta))

# %% ../nbs/00_core.ipynb #01e0b545
@patch
async def _set_trashed(self:File, trashed):
    return self.update(await self.drive.client.files.update(file_id=self.id, trashed=trashed, fields=FIELDS))

@patch
async def trash(self:File):
    "Move to the trash (recoverable for 30 days)"
    sys.audit('solvedrive.File.trash')
    return await self._set_trashed(True)

@patch
async def untrash(self:File):
    "Restore from the trash"
    return await self._set_trashed(False)

@patch
async def delete(self:File):
    "Delete permanently, skipping the trash"
    sys.audit('solvedrive.File.delete')
    return await self.drive.client.files.delete(file_id=self.id)

# %% ../nbs/00_core.ipynb #72defcd0
@patch
def _gfiles(self:Files): return self.drive.client._gservice.files()

@patch
async def refresh(self:Files, fields=FIELDS):
    "Batch re-fetch metadata for all files"
    if not self: return self
    res = self.drive.client.batch_get([(f.id, self._gfiles().get(fileId=f.id, fields=fields)) for f in self])
    for f in self: f.update(dict2obj(res[f.id]))
    return self

@patch
async def _set_trashed(self:Files, trashed):
    if not self: return self
    res = self.drive.client.batch_get([(f.id, self._gfiles().update(fileId=f.id, body=dict(trashed=trashed), fields=FIELDS)) for f in self])
    for f in self: f.update(dict2obj(res[f.id]))
    return self

@patch
async def trash(self:Files):
    "Batch move all files to the trash"
    sys.audit('solvedrive.Files.trash')
    return await self._set_trashed(True)

@patch
async def untrash(self:Files):
    "Batch restore all files from the trash"
    return await self._set_trashed(False)

@patch
async def delete(self:Files):
    "Batch delete all files permanently"
    sys.audit('solvedrive.Files.delete')
    if self: self.drive.client.batch_get([(f.id, self._gfiles().delete(fileId=f.id)) for f in self])

# %% ../nbs/00_core.ipynb #6d5ec299
@patch
async def share(self:File,
    email=None,      # User or group to share with (anyone-with-the-link if None)
    role='reader',   # 'reader', 'commenter', 'writer', or 'owner'
    notify=False,    # Send the grantee a notification email?
):
    "Grant access, returning the new permission"
    sys.audit('solvedrive.File.share')
    meta = dict(file_id=self.id, role=role, send_notification_email=notify)
    if email: meta.update(type='user', email_address=email)
    else: meta['type'] = 'anyone'
    return await self.drive.client.permissions.create(**meta)

@patch(as_prop=True)
async def permissions(self:File):
    r = await self.drive.client.permissions.list(file_id=self.id, fields='permissions(id,type,role,emailAddress)')
    return r.permissions

@patch
async def unshare(self:File, permission_id):
    "Revoke a permission by id"
    return await self.drive.client.permissions.delete(file_id=self.id, permission_id=permission_id)
