"""Fill in a module description here

Docs: https://answerDotAI.github.io/solvedrivecore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #6532188c
def foo(): pass
