"""User facing API for solvedrive

Docs: https://answerDotAI.github.io/solvedrive/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['FIELDS', 'FOLDER_MIME', 'DRIVE_FIELDS', 'GDrive', 'hsize', 'File', 'Folder', 'Files', 'Drive', 'Drives']

# %% ../nbs/00_core.ipynb #4d53f263
from fastcore.all import *
from fastgws import Drive as FGWSDrive
from fastgws.auth import *

import sys

# %% ../nbs/00_core.ipynb #f4e588b0
FIELDS = 'id,name,mimeType,size,modifiedTime,parents,trashed,webViewLink'

class GDrive(GetAttr):
    _default = 'api'
    def __init__(self, creds): self.api = FGWSDrive(creds=creds)

    async def about(self):
        "User resource with `email` attribute"
        d = await self.api.about.get(fields='user')
        return AttrDict(d.user, email=d.user.emailAddress)

# %% ../nbs/00_core.ipynb #fe25d3be
FOLDER_MIME = 'application/vnd.google-apps.folder'

def hsize(n):
    "Human-readable byte size"
    for u in ' KMGT':
        if n < 1024: return f'{n:.0f}{u.strip()}B' if u==' ' else f'{n:.1f}{u}B'
        n /= 1024
    return f'{n:.1f}PB'

def _mtype(m): return m.split('.')[-1] if m.startswith('application/vnd.google-apps') else m

def _link(f):
    "File name as an anchor opening it in Drive in a new tab"
    nm = f.get('name') or ''
    return f'<a href="{url}" target="_blank">{nm}</a>' if (url:=f.get('webViewLink')) else nm

class File(AttrDict):
    def __init__(self, client, d):
        super().__init__(d)
        object.__setattr__(self, '_client', client)

    def _desc(self, nm):
        sz = f', {hsize(int(self.size))}' if self.get('size') else ''
        trash = '🗑' if self.get('trashed') else ''
        return f'{type(self).__name__}({self.id}: {trash}{nm} ({_mtype(self.get("mimeType", ""))}{sz}) {self.get("modifiedTime", "")})'

    def __repr__(self): return self._desc(self.get('name', ''))
    def _repr_markdown_(self): return self._desc(_link(self))

    async def refresh(self, fields=FIELDS):
        self.update(await self._client.files.get(file_id=self.id, fields=fields, supports_all_drives=True))
        return self

    @classmethod
    async def fetch(cls, client, id): return await cls(client, dict(id=id)).refresh()

class Folder(File): pass

def _fid(f): return f.id if isinstance(f, File) else f

def _mk_file(client, d):
    cls = Folder if d.get('mimeType')==FOLDER_MIME else File
    return cls(client, d)

# %% ../nbs/00_core.ipynb #a5cc3392
@patch
async def upload(self:GDrive,
    path=None,   # File to upload
    name=None,   # Name in Drive (defaults to `path`'s name)
    data=None,   # Content bytes, as an alternative to `path`
    mime=None,   # Content type (guessed from `name` if not given)
    folder=None, # Destination `Folder` or folder id (default: My Drive root)
):
    "Upload a file to Drive, returning the new `File`"
    if path: name = name or Path(path).name
    meta = dict(name=name)
    if folder: meta['parents'] = [_fid(folder)]
    r = await self.api.files.upload(media=path or data, media_type=mime, fields=FIELDS, supports_all_drives=True, **meta)
    return _mk_file(self, r)

# %% ../nbs/00_core.ipynb #d7fe7a99
def _file_row(f):
    sz = hsize(int(f.size)) if f.get('size') else ''
    return f'| {f.id} | {"🗑" if f.get("trashed") else ""}{_link(f)} | {_mtype(f.get("mimeType") or "")} | {sz} | {(f.get("modifiedTime") or "")[:10]} |'

_file_hdr = '| id | name | type | size | modified |\n|-|-|-|-|-|\n'
class Files(L):
    def __init__(self, d, *rest, client=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self._client = client

    def _repr_markdown_(self): return _file_hdr + '\n'.join(self.map(_file_row))

@patch
async def search_files(self:GDrive, q=None, max_results=20, fields=FIELDS, **kwargs):
    "Search every drive you can see: My Drive, files shared with you, and all shared drives"
    kwargs = dict(corpora='allDrives', include_items_from_all_drives=True, supports_all_drives=True) | kwargs
    r = await self.api.files.list(q=q, page_size=max_results, fields=f'files({fields})', **kwargs)
    return Files(L(r.get('files') or []).map(lambda o: _mk_file(self, o)), client=self)

# %% ../nbs/00_core.ipynb #c5cc0e5e
_exports = {'application/vnd.google-apps.document': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.google-apps.spreadsheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.google-apps.presentation': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.google-apps.drawing': 'image/png'}

@patch
async def download(self:File,
    save=None, # Optional path to also write the bytes to (a directory uses the file's name)
    mime=None, # Export format for Google-native files
):
    "File content as bytes; Google-native files are exported (docx/xlsx/pptx by default)"
    native = self.mimeType.startswith('application/vnd.google-apps')
    if not native:
        if mime: raise ValueError(f'`mime` is for exporting Google-native files; {self.name} is {self.mimeType}')
        r = await self._client.files.get(file_id=self.id, alt='media', raw_=True, supports_all_drives=True)
    else: r = await self._client.files.export(file_id=self.id, mime_type=mime or _exports[self.mimeType], raw_=True)
    data = r.content
    if save:
        p = Path(save)
        if p.is_dir(): p = p/self.name
        p.write_bytes(data)
    return data

# %% ../nbs/00_core.ipynb #52081533
@patch
async def create_folder(self:GDrive, name, parent=None):
    "Create a folder, returning the new `Folder`"
    meta = dict(name=name, mime_type=FOLDER_MIME, fields=FIELDS, supports_all_drives=True)
    if parent: meta['parents'] = [_fid(parent)]
    return Folder(self, await self.api.files.create(**meta))

@patch
async def ls(self:Folder, q=None, **kwargs):
    "Search within this folder"
    qs = f"'{self.id}' in parents and trashed=false"
    if q: qs = f'{qs} and ({q})'
    return await self._client.search_files(qs, **kwargs)

@patch
@delegates(GDrive.upload)
async def upload(self:Folder, path=None, **kwargs):
    "Upload into this folder"
    return await self._client.upload(path, folder=self, **kwargs)

# %% ../nbs/00_core.ipynb #86d374ef
DRIVE_FIELDS = 'id,name,capabilities'

def _drole(d):
    "Role implied by drive `capabilities`"
    c = d.get('capabilities') or {}
    for cap,role in [('canManageMembers','organizer'),('canTrashChildren','fileOrganizer'),
        ('canAddChildren','writer'),('canComment','commenter')]:
        if c.get(cap): return role
    return 'reader'

def _dlink(d):
    "Drive name as an anchor opening it in Drive in a new tab"
    url = 'https://drive.google.com/drive/my-drive' if d.id=='root' else f'https://drive.google.com/drive/folders/{d.id}'
    return f'<a href="{url}" target="_blank">{d.name}</a>'

class Drive(AttrDict):
    def __init__(self, client, d):
        super().__init__(d)
        object.__setattr__(self, '_client', client)

    @property
    def role(self): return 'owner' if self.id=='root' else _drole(self)
    def _desc(self, nm): return f'{type(self).__name__}({self.id}: {nm}, {self.role})'
    def __repr__(self): return self._desc(self.name)
    def _repr_markdown_(self): return self._desc(_dlink(self))

def _drive_row(d): return f'| {d.id} | {_dlink(d)} | {d.role} |'
_drive_hdr = '| id | name | role |\n|-|-|-|\n'
class Drives(L):
    def __init__(self, d, *rest, client=None, **kwargs):
        super().__init__(d, *rest, **kwargs)
        self._client = client

    def _repr_markdown_(self): return _drive_hdr + '\n'.join(self.map(_drive_row))

@patch
async def list_drives(self:GDrive, fields=DRIVE_FIELDS, **kwargs):
    "Your drives: My Drive first, then every shared drive you're a member of"
    r = await self.api.drives.list(fields=f'drives({fields})', **kwargs)
    ds = [dict(id='root', name='My Drive')] + list(r.get('drives') or [])
    return Drives(L(ds).map(lambda o: Drive(self, o)), client=self)

# %% ../nbs/00_core.ipynb #fb7d6f57
@patch
async def search_files(self:Drive, q=None, **kwargs):
    "Search within this drive"
    scope = dict(corpora='user') if self.id=='root' else dict(corpora='drive', drive_id=self.id)
    return await self._client.search_files(q, **scope, **kwargs)

@patch(as_prop=True)
async def root(self:Drive):
    "The drive's root `Folder`"
    return await Folder.fetch(self._client, self.id)

# %% ../nbs/00_core.ipynb #859523ef
@patch
async def rename(self:File, name):
    "Rename to `name`"
    return self.update(await self._client.files.update(file_id=self.id, name=name, fields=FIELDS, supports_all_drives=True))

@patch
async def move(self:File, folder):
    "Move into `folder` (a `Folder` or folder id)"
    return self.update(await self._client.files.update(file_id=self.id, add_parents=_fid(folder),
        remove_parents=','.join(self.get('parents') or []), fields=FIELDS, supports_all_drives=True))

@patch
async def copy(self:File, name=None, folder=None):
    "Server-side copy, optionally renamed into `folder`; returns the new `File`"
    meta = dict(file_id=self.id, fields=FIELDS, supports_all_drives=True)
    if name: meta['name'] = name
    if folder: meta['parents'] = [_fid(folder)]
    return _mk_file(self._client, await self._client.files.copy(**meta))

# %% ../nbs/00_core.ipynb #01e0b545
@patch
async def _set_trashed(self:File, trashed):
    return self.update(await self._client.files.update(file_id=self.id, trashed=trashed, fields=FIELDS, supports_all_drives=True))

@patch
async def trash(self:File):
    "Move to the trash (recoverable for 30 days)"
    sys.audit('solvedrive.File.trash')
    return await self._set_trashed(True)

@patch
async def untrash(self:File):
    "Restore from the trash"
    return await self._set_trashed(False)

@patch
async def delete(self:File):
    "Delete permanently, skipping the trash"
    sys.audit('solvedrive.File.delete')
    return await self._client.files.delete(file_id=self.id, supports_all_drives=True)

# %% ../nbs/00_core.ipynb #72defcd0
@patch
async def refresh(self:Files, fields=FIELDS):
    "Re-fetch metadata for all files"
    await parallel_async(File.refresh, self, fields)
    return self

@patch
async def _set_trashed(self:Files, trashed):
    await parallel_async(File._set_trashed, self, trashed)
    return self

@patch
async def trash(self:Files):
    "Move all files to the trash"
    sys.audit('solvedrive.Files.trash')
    return await self._set_trashed(True)

@patch
async def untrash(self:Files):
    "Restore all files from the trash"
    return await self._set_trashed(False)

@patch
async def delete(self:Files):
    "Delete all files permanently"
    sys.audit('solvedrive.Files.delete')
    await parallel_async(File.delete, self)

# %% ../nbs/00_core.ipynb #6d5ec299
@patch
async def share(self:File,
    email=None,      # User or group to share with (anyone-with-the-link if None)
    role='reader',   # 'reader', 'commenter', 'writer', or 'owner'
    notify=False,    # Send the grantee a notification email?
):
    "Grant access, returning the new permission"
    sys.audit('solvedrive.File.share')
    meta = dict(file_id=self.id, role=role, send_notification_email=notify, supports_all_drives=True)
    if email: meta.update(type='user', email_address=email)
    else: meta['type'] = 'anyone'
    return await self._client.permissions.create(**meta)

@patch(as_prop=True)
async def permissions(self:File):
    r = await self._client.permissions.list(file_id=self.id, fields='permissions(id,type,role,emailAddress)', supports_all_drives=True)
    return r.permissions

@patch
async def unshare(self:File, permission_id):
    "Revoke a permission by id"
    return await self._client.permissions.delete(file_id=self.id, permission_id=permission_id, supports_all_drives=True)
